# Generated by Django 5.1.6 on 2025-02-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_placement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
